apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
    #where are the config files for k8. which files to watch (.yaml)
    # the point is when we make a change to any of those files, skaffold will build the deployments automatically
    # otherwise we have to run kubectl apply -f each time we make changes to our code
    # when skaffold is starting, will delete all found configurations and then build them again
    # when stopping skaffold, will find all objects created and delete them
    # in this array list all the files you want to sync
      - ./infra/k8s/*
build:
  local:
  # push: false means to don't push to docker hub
    push: false    
  # which folder/project to check for changes
  # the point is or update the files in the src folder or rebuild the image when there is a change outside it e.g. in package.json
  artifacts:
    # which image to rebuild when needed
    - image: exalkas/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
        # src is usually for react unless there is such a structure in node
          # - src: 'src/**/*.js'
          - src: 'src/**/*.ts'
          # sync the file inside of our current container
          # the "." means that take the file from current dir and copy into the corresponding folder in the image
            dest: .
    - image: exalkas/ticketingclient
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
        # src is usually for react unless there is such a structure in node
          # - src: 'src/**/*.js'
          - src: '**/*.js'
          # sync the file inside of our current container
          # the "." means that take the file from current dir and copy into the corresponding folder in the image
            dest: .
    # for more microservices just copy the artifacts and replace the proper values
        # which image to rebuild when needed
    # - image: exalkas/client
    #   context: client
    #   docker:
    #     dockerfile: Dockerfile
    #   sync:
    #     manual:
    #     # src is usually for react unless there is such a structure in node
    #       - src: 'src/**/*.js'
    #         dest: .